import type {
  AppState,
  CommsEvent,
  EdgeApproval,
  Integration,
  Meeting,
  Member,
  Prospect,
  Touchpoint,
  Trade,
} from '../types'

const members: Member[] = [
  {
    id: 'm-voss',
    name: 'Eleanor Voss',
    kind: 'family-office',
    company: 'Voss Family Office',
    title: 'Principal',
    email: 'eleanor@vossfo.com',
    phone: '(212) 555-0144',
    city: 'New York, NY',
    since: '2019-03-12',
    aum: 42_400_000,
    riskProfile: 'Moderate-conservative · Nitrogen 48',
    strategy: 'Preserve principal across the third generation. 60/25/15 public / PE / cash. Open to a $4–6M commitment into Solyco Fund IV if liquidity from the Park Ave sale lands in Q4. Prefers separately managed taxable account for new PE capital calls.',
    missingInfo: [
      'Updated estate-plan summary (last received 2023)',
      'K-1 delivery preference for new entity',
      'Beneficiary designation on IRA-8841',
    ],
    interests: ['Equestrian', 'Modernist architecture', 'MoMA patronage'],
    hobbies: ['Dressage', 'Weekend Hudson house'],
    favorites: {
      alcohol: 'Grower champagne — Pierre Péters, not vintage Krug',
      restaurants: ['The Grill', 'Via Carota', 'Casa Lever'],
      other: ['Peonies, never lilies', 'Handwritten notes over email'],
    },
    dontTouch: [
      'Do not mention the 2022 divorce',
      'Avoid crypto / digital assets — she shut this down twice',
      'Never raise the Greenwich house; it is a sore subject with the children',
    ],
    family: [
      { id: 'f-v1', name: 'Clara Voss', relation: 'Daughter, 28', notes: 'Works at Sotheby’s. Interested in art-backed lending.' },
      { id: 'f-v2', name: 'Henry Voss', relation: 'Son, 24', notes: 'NYU Stern 2nd year. Asking about a donor-advised fund.' },
      { id: 'f-v3', name: 'Margaret Voss', relation: 'Mother, 81', notes: 'Lives in Palm Beach Nov–Apr. Healthcare directive outstanding.' },
    ],
    accounts: [
      { id: 'a-v1', code: 'VOSS-TX-110', name: 'Voss Taxable SMA', type: 'taxable', aum: 18_200_000 },
      { id: 'a-v2', code: 'VOSS-TR-204', name: 'Voss Dynasty Trust', type: 'trust', aum: 16_800_000 },
      { id: 'a-v3', code: 'VOSS-IRA-8841', name: 'Eleanor Rollover IRA', type: 'ira', aum: 7_400_000 },
    ],
    products: ['Fund IV', 'Taxable SMA', 'Municipal sleeve', 'Trust services'],
    notes: 'Came in via Hale introduction. Decision maker; consults Clara on anything “public-facing.” Quarterly in person, monthly call.',
    memories: [
      { id: 'mem-v1', kind: 'personal', text: 'Rides Tuesday/Thursday mornings at Claremont. Never book 8–10am ET those days.', createdAt: '2026-03-04' },
      { id: 'mem-v2', kind: 'preference', text: 'Hates the word “holistic.” Use “coordinated.”', createdAt: '2025-11-12' },
      { id: 'mem-v3', kind: 'business', text: 'Park Avenue duplex under contract; expected close mid-October.', createdAt: '2026-07-22' },
    ],
    lastTouch: '2026-08-08',
    nextTouch: '2026-08-15',
  },
  {
    id: 'm-chen',
    name: 'Marcus Chen',
    kind: 'portfolio',
    company: 'Northline Robotics',
    title: 'Founder & CEO',
    email: 'marcus@northline.co',
    phone: '(650) 555-0190',
    city: 'Palo Alto, CA',
    since: '2023-06-01',
    aum: 9_100_000,
    riskProfile: 'Aggressive · Nitrogen 72',
    strategy: 'Founder liquidity after Series C. Keep 70% in diversified public book, 20% concentrated tech, 10% dry powder for a second company. Exploring 10b5-1 on remaining Northline shares after lockup in November.',
    missingInfo: ['Spouse risk-tolerance questionnaire', '10b5-1 draft from outside counsel'],
    interests: ['Trail running', 'Vintage Leicas', 'Bay Area food'],
    hobbies: ['Saturday long run at Rancho San Antonio'],
    favorites: {
      alcohol: 'High West Campfire — one pour, never a bottle gift',
      restaurants: ['Saison', 'Lazy Bear'],
      other: ['Black coffee only', 'Texts > email'],
    },
    dontTouch: ['Do not discuss the failed 2021 robotics roll-up', 'Skip politics'],
    family: [
      { id: 'f-c1', name: 'Ava Chen', relation: 'Spouse', notes: 'Pediatrician at Stanford. Separate taxable account TBD.' },
      { id: 'f-c2', name: 'Leo Chen', relation: 'Son, 4', notes: '529 not yet opened — easy win.' },
    ],
    accounts: [
      { id: 'a-c1', code: 'CHEN-TX-330', name: 'Chen Founder Taxable', type: 'taxable', aum: 6_400_000 },
      { id: 'a-c2', code: 'CHEN-ENT-12', name: 'Northline HoldCo', type: 'entity', aum: 2_700_000 },
    ],
    products: ['Founder liquidity book', '10b5-1 planning', '529', 'QSBS tracking'],
    notes: 'Solyco led the Series B. Marcus treats us as the “personal CFO.” Fast decisions, hates decks.',
    memories: [
      { id: 'mem-c1', kind: 'timing', text: 'Best window is 6:30am PT before standup.', createdAt: '2026-01-09' },
      { id: 'mem-c2', kind: 'phrase', text: 'He says “just tell me the trade.” Lead with the action.', createdAt: '2026-04-18' },
    ],
    lastTouch: '2026-08-12',
    nextTouch: '2026-08-20',
  },
  {
    id: 'm-shah',
    name: 'Priya Shah',
    kind: 'lp',
    company: 'Shah Family Trust',
    title: 'Trustee',
    email: 'priya@shahtrust.org',
    phone: '(312) 555-0177',
    city: 'Chicago, IL',
    since: '2020-09-18',
    aum: 27_600_000,
    riskProfile: 'Moderate · Nitrogen 55',
    strategy: 'Income + modest growth. Heavy muni book. Considering a $3M add to Fund IV and a direct into a Midwest industrial roll-up. Wants a formal IPS refresh this quarter.',
    missingInfo: ['Updated IPS signature', 'Brother’s contact as successor trustee'],
    interests: ['Indian classical music', 'University of Chicago trustee work'],
    hobbies: ['Saturday farmer’s market with her father'],
    favorites: {
      alcohol: 'Does not drink',
      restaurants: ['Smyth', 'Kasama'],
      other: ['Masala chai, no sweetener', 'Prefers Zoom to phone'],
    },
    dontTouch: ['Do not pitch insurance products — prior advisor burned her'],
    family: [
      { id: 'f-s1', name: 'Ravi Shah', relation: 'Father, 78', notes: 'Still reviews every statement. Print packet for him.' },
      { id: 'f-s2', name: 'Anika Shah', relation: 'Sister, 41', notes: 'Lives in London. Not on the trust. Sensitive.' },
    ],
    accounts: [
      { id: 'a-s1', code: 'SHAH-TR-091', name: 'Shah Family Trust', type: 'trust', aum: 21_000_000 },
      { id: 'a-s2', code: 'SHAH-TX-092', name: 'Priya Joint Taxable', type: 'taxable', aum: 6_600_000 },
    ],
    products: ['Fund III', 'Fund IV (considering)', 'Muni SMA', 'IPS'],
    notes: 'Came from a wire-house. Trusts process. Always send a written recap the same day.',
    memories: [
      { id: 'mem-s1', kind: 'preference', text: 'Never schedule Fridays — she flies to see her father.', createdAt: '2024-06-02' },
    ],
    lastTouch: '2026-07-30',
    nextTouch: '2026-08-15',
  },
  {
    id: 'm-okonkwo',
    name: 'David Okonkwo',
    kind: 'advisor-client',
    company: 'Harbor Ridge Holdings',
    title: 'Managing Partner',
    email: 'david@harborridge.com',
    phone: '(404) 555-0112',
    city: 'Atlanta, GA',
    since: '2021-01-20',
    aum: 14_800_000,
    riskProfile: 'Moderate-aggressive · Nitrogen 64',
    strategy: 'Barbell: public growth + private credit. Interested in Solyco’s new private-credit sleeve. Has two operating companies that may need cash-management sweep.',
    missingInfo: ['Operating-company bank statements', 'Personal life insurance in-force illustration'],
    interests: ['Atlanta United', 'Collecting first-edition West African literature'],
    hobbies: ['Golf at East Lake'],
    favorites: {
      alcohol: 'Macallan 18, neat',
      restaurants: ['Atlas', 'Kimball House'],
      other: ['Braves tickets over fruit baskets'],
    },
    dontTouch: ['Do not bring up the 2024 failed recap of Harbor II'],
    family: [
      { id: 'f-o1', name: 'Nia Okonkwo', relation: 'Spouse', notes: 'Runs a nonprofit. DAF conversation is open.' },
    ],
    accounts: [
      { id: 'a-o1', code: 'OKON-TX-441', name: 'Okonkwo Taxable', type: 'taxable', aum: 8_900_000 },
      { id: 'a-o2', code: 'OKON-ENT-18', name: 'Harbor Ridge Holdings', type: 'entity', aum: 5_900_000 },
    ],
    products: ['Private credit sleeve', 'Cash sweep', 'DAF'],
    notes: 'Introduced two other Atlanta operators. Treat as a node, not a single relationship.',
    memories: [
      { id: 'mem-o1', kind: 'personal', text: 'Son just committed to Morehouse. Education-funding talk is timely.', createdAt: '2026-08-01' },
    ],
    lastTouch: '2026-08-05',
    nextTouch: '2026-08-19',
  },
  {
    id: 'm-park',
    name: 'Helen Park',
    kind: 'family-office',
    company: 'Park & Alden',
    title: 'CIO',
    email: 'helen@parkaldan.com',
    phone: '(206) 555-0188',
    city: 'Seattle, WA',
    since: '2022-04-04',
    aum: 61_200_000,
    riskProfile: 'Moderate · Nitrogen 52',
    strategy: 'Institutional-grade family office. Solyco is a satellite PE manager, not the OCIO. She wants cleaner capital-call notices and a single positions file. Evaluating us against two other GPs for a $10M Fund IV ticket.',
    missingInfo: ['Side-letter redlines from their counsel'],
    interests: ['Pacific Northwest hiking', 'Ceramic collecting'],
    hobbies: ['Early ferry to Bainbridge on Sundays'],
    favorites: {
      alcohol: 'Willamette Pinot — Bergström',
      restaurants: ['Canlis', 'The Walrus and the Carpenter'],
      other: ['No swag. Ever.'],
    },
    dontTouch: ['Do not compare Solyco to endowment peers — she finds it amateur'],
    family: [
      { id: 'f-p1', name: 'Alden Park', relation: 'Brother / co-trustee', notes: 'Silent. Helen speaks for the office.' },
    ],
    accounts: [
      { id: 'a-p1', code: 'PARK-ENT-01', name: 'Park & Alden PE', type: 'entity', aum: 44_000_000 },
      { id: 'a-p2', code: 'PARK-TR-77', name: 'Park Dynasty Trust', type: 'trust', aum: 17_200_000 },
    ],
    products: ['Fund III', 'Fund IV (in diligence)', 'Co-invest notices'],
    notes: 'Most sophisticated LP. Over-prepare. Numbers first, narrative second.',
    memories: [
      { id: 'mem-p1', kind: 'preference', text: 'Send materials 48 hours before any meeting or she cancels.', createdAt: '2023-09-14' },
    ],
    lastTouch: '2026-08-11',
    nextTouch: '2026-08-25',
  },
  {
    id: 'm-whitaker',
    name: 'James Whitaker',
    kind: 'portfolio',
    company: 'Whitaker Industrial',
    title: 'Chairman',
    email: 'jwhitaker@whitakerind.com',
    phone: '(216) 555-0133',
    city: 'Cleveland, OH',
    since: '2018-11-02',
    aum: 22_000_000,
    riskProfile: 'Conservative · Nitrogen 38',
    strategy: 'Post-exit chairman. Capital preservation and a clean succession for the remaining 12% stake. Talking about a sale of that stub in 2027. Needs a coordinated tax + estate plan with their Cleveland counsel.',
    missingInfo: ['Cost basis on stub shares', 'Life insurance in-force'],
    interests: ['Lake Erie sailing', 'Cleveland Orchestra'],
    hobbies: ['Wooden-boat restoration'],
    favorites: {
      alcohol: 'Old Forester 1920',
      restaurants: ['Lola', 'Mabel’s BBQ'],
      other: ['Browns season tickets — 40-yard line'],
    },
    dontTouch: ['Do not criticize the management team we installed', 'Avoid national politics'],
    family: [
      { id: 'f-w1', name: 'Ruth Whitaker', relation: 'Spouse', notes: 'Makes the philanthropy decisions.' },
      { id: 'f-w2', name: 'Sam Whitaker', relation: 'Son, 33', notes: 'Works at the company. Wants a seat on the family investment committee.' },
    ],
    accounts: [
      { id: 'a-w1', code: 'WHIT-TX-208', name: 'Whitaker Taxable', type: 'taxable', aum: 11_500_000 },
      { id: 'a-w2', code: 'WHIT-TR-209', name: 'Whitaker Revocable', type: 'trust', aum: 10_500_000 },
    ],
    products: ['Post-exit SMA', 'Estate coordination', 'Charitable remainder'],
    notes: 'Original Solyco deal. Treat with founder-level care. Ruth should be invited to the next annual.',
    memories: [
      { id: 'mem-w1', kind: 'personal', text: 'Anniversary is September 3. Send something from a Cleveland maker, not a catalog.', createdAt: '2025-09-01' },
    ],
    lastTouch: '2026-07-21',
    nextTouch: '2026-08-18',
  },
  {
    id: 'm-alvarez',
    name: 'Sofia Alvarez',
    kind: 'advisor-client',
    company: 'Alvarez Revocable Trust',
    title: 'Grantor',
    email: 'sofia@alvarezmail.com',
    phone: '(305) 555-0160',
    city: 'Miami, FL',
    since: '2024-02-14',
    aum: 6_700_000,
    riskProfile: 'Moderate · Nitrogen 50',
    strategy: 'Recently widowed. Consolidate three custodians into Solyco’s Orion book. Focus on income, Florida homestead, and a plan for the two adult children who do not get along.',
    missingInfo: [
      'Death certificate certified copy',
      'Beneficiary confirmations on two IRAs',
      'Condo HOA estoppel',
    ],
    interests: ['Orchids', 'New World Symphony'],
    hobbies: ['Early walks on South Pointe'],
    favorites: {
      alcohol: 'Albariño, lightly chilled',
      restaurants: ['Mandolin', 'Joe’s Stone Crab (takeout only)'],
      other: ['White flowers only'],
    },
    dontTouch: ['Do not rush the consolidation', 'Never take a side between the children'],
    family: [
      { id: 'f-a1', name: 'Diego Alvarez', relation: 'Son, 36', notes: 'Lives in Houston. Wants distributions.' },
      { id: 'f-a2', name: 'Camila Alvarez', relation: 'Daughter, 31', notes: 'Lives in Miami. Wants the condo kept.' },
    ],
    accounts: [
      { id: 'a-al1', code: 'ALVA-TR-55', name: 'Alvarez Revocable', type: 'trust', aum: 4_200_000 },
      { id: 'a-al2', code: 'ALVA-IRA-56', name: 'Sofia Inherited IRA', type: 'ira', aum: 2_500_000 },
    ],
    products: ['Consolidation', 'Income sleeve', 'Family meeting facilitation'],
    notes: 'High-touch. Weekly for 90 days post-onboarding, then monthly.',
    memories: [
      { id: 'mem-al1', kind: 'personal', text: 'Luis died in January 2026. She still uses “we” — do not correct her.', createdAt: '2026-02-20' },
    ],
    lastTouch: '2026-08-13',
    nextTouch: '2026-08-16',
  },
  {
    id: 'm-hale',
    name: 'Robert Hale',
    kind: 'lp',
    company: 'Hale Partners',
    title: 'Founder',
    email: 'rhale@halepartners.com',
    phone: '(617) 555-0104',
    city: 'Boston, MA',
    since: '2017-05-09',
    aum: 33_500_000,
    riskProfile: 'Moderate-aggressive · Nitrogen 61',
    strategy: 'Multi-fund LP and our best referral source. Wants a co-invest on the next industrial deal. Talking about putting his two partners into a feeder so they can come in at a lower minimum.',
    missingInfo: ['Feeder term-sheet draft'],
    interests: ['Celtics', 'Wooden boat racing in Marblehead'],
    hobbies: ['Dawn rowing on the Charles'],
    favorites: {
      alcohol: 'WhistlePig 15',
      restaurants: ['Menton', 'Neptune Oyster'],
      other: ['Red Sox tickets when the Yankees are in town'],
    },
    dontTouch: ['Do not mention the 2019 side-letter dispute — it is closed'],
    family: [
      { id: 'f-h1', name: 'June Hale', relation: 'Spouse', notes: 'Joins the annual dinner. Allergic to shellfish.' },
    ],
    accounts: [
      { id: 'a-h1', code: 'HALE-ENT-03', name: 'Hale Partners LP', type: 'entity', aum: 28_000_000 },
      { id: 'a-h2', code: 'HALE-TX-04', name: 'Robert Hale Taxable', type: 'taxable', aum: 5_500_000 },
    ],
    products: ['Fund II', 'Fund III', 'Fund IV', 'Co-invest', 'Feeder'],
    notes: 'Introduced Eleanor Voss. Treat as a partner, not a client.',
    memories: [
      { id: 'mem-h1', kind: 'timing', text: 'Best call window 6:45am ET from the boathouse parking lot.', createdAt: '2022-08-11' },
    ],
    lastTouch: '2026-08-09',
    nextTouch: '2026-08-22',
  },
]

const prospects: Prospect[] = [
  {
    id: 'p-smith',
    name: 'John Smith',
    company: 'Smith Manufacturing',
    title: 'Owner & CEO',
    website: 'https://smithmfg.example',
    linkedin: 'https://linkedin.com/in/johnsmith-mfg',
    industry: 'Precision manufacturing · industrial',
    email: 'john@smithmfg.example',
    phone: '(937) 555-0199',
    city: 'Dayton, OH',
    stage: 'discovery',
    relationshipStatus: 'meeting-set',
    objective: 'Discuss business liquidity, cash management, succession planning, and personal wealth planning.',
    products: ['Business liquidity', 'Cash management', 'Succession', 'Personal wealth'],
    tone: 'Professional but conversational',
    notes: 'Second-generation manufacturer. 180 employees. Thinking about a minority recap in 24 months. Brother is COO and may not want to sell.',
    priorNotes: 'Introduced by James Whitaker at the Cleveland Orchestra gala. John mentioned rising working-capital needs and a key-person gap if he stepped back.',
    lastTouch: '2026-08-07',
    nextTouch: '2026-08-15',
    owner: 'James',
    source: 'Whitaker referral',
  },
  {
    id: 'p-ortiz',
    name: 'Lena Ortiz',
    company: 'Ortiz Dental Group',
    title: 'Founder',
    website: 'https://ortizdental.example',
    linkedin: 'https://linkedin.com/in/lenaortizdds',
    industry: 'Healthcare services',
    email: 'lena@ortizdental.example',
    phone: '(480) 555-0121',
    city: 'Scottsdale, AZ',
    stage: 'outreach',
    relationshipStatus: 'warm',
    objective: 'Open a conversation about a DSO recap and personal planning after a four-clinic expansion.',
    products: ['Practice liquidity', 'Personal wealth'],
    tone: 'Warm, peer-to-peer',
    notes: 'Four clinics, exploring a DSO. Husband is a commercial real-estate broker.',
    priorNotes: 'Met at a Phoenix PE dinner. Asked a sharp question about after-tax proceeds.',
    lastTouch: '2026-08-02',
    nextTouch: '2026-08-17',
    owner: 'James',
    source: 'Conference',
  },
  {
    id: 'p-nguyen',
    name: 'Thomas Nguyen',
    company: 'Redwood Logistics',
    title: 'CEO',
    website: 'https://redwoodlog.example',
    linkedin: 'https://linkedin.com/in/tnguyen-log',
    industry: 'Third-party logistics',
    email: 'thomas@redwoodlog.example',
    phone: '(503) 555-0148',
    city: 'Portland, OR',
    stage: 'proposal',
    relationshipStatus: 'active-dialogue',
    objective: 'Present a minority-growth term sheet and a personal liquidity sleeve.',
    products: ['Growth equity', 'Founder liquidity'],
    tone: 'Direct, numbers-first',
    notes: 'Wants to stay CEO. Valuation gap of about a turn. Sister is CFO.',
    priorNotes: 'Three calls. Sent a one-pager on 8/6. Waiting on 2025 audit.',
    lastTouch: '2026-08-06',
    nextTouch: '2026-08-16',
    owner: 'James',
    source: 'Inbound via Hale',
  },
  {
    id: 'p-brennan',
    name: 'Claire Brennan',
    company: 'Brennan Capital',
    title: 'Managing Director',
    website: 'https://brennancap.example',
    linkedin: 'https://linkedin.com/in/clairebrennan',
    industry: 'Lower-middle-market PE',
    email: 'claire@brennancap.example',
    phone: '(312) 555-0182',
    city: 'Chicago, IL',
    stage: 'nurture',
    relationshipStatus: 'warm',
    objective: 'Stay close as a potential co-GP / LP hybrid on Midwest industrials.',
    products: ['Co-invest', 'Fund IV'],
    tone: 'Peer, understated',
    notes: 'Runs a $400M fund. Not a client — a peer who could allocate.',
    priorNotes: 'Coffee in River North in June. She liked our Whitaker write-up.',
    lastTouch: '2026-06-18',
    nextTouch: '2026-08-21',
    owner: 'James',
    source: 'Peer network',
  },
  {
    id: 'p-rao',
    name: 'Amit Rao',
    company: 'Rao Precision Tools',
    title: 'President',
    website: 'https://raotools.example',
    linkedin: 'https://linkedin.com/in/amitrao',
    industry: 'Industrial tooling',
    email: 'amit@raotools.example',
    phone: '(248) 555-0170',
    city: 'Troy, MI',
    stage: 'research',
    relationshipStatus: 'cold',
    objective: 'First-touch around succession. Father still chairman at 79.',
    products: ['Succession', 'Minority recap'],
    tone: 'Respectful, unhurried',
    notes: 'Third generation. Auto-adjacent. Rumored that a strategic circled last year.',
    priorNotes: '',
    lastTouch: '2026-07-12',
    nextTouch: '2026-08-18',
    owner: 'James',
    source: 'Desk research',
  },
  {
    id: 'p-lin',
    name: 'Margaret Lin',
    company: 'Lin Properties',
    title: 'Managing Partner',
    website: 'https://linproperties.example',
    linkedin: 'https://linkedin.com/in/margaretlin',
    industry: 'Real estate operating',
    email: 'margaret@linproperties.example',
    phone: '(415) 555-0155',
    city: 'San Francisco, CA',
    stage: 'outreach',
    relationshipStatus: 'referral',
    objective: 'Introduce cash-management and a personal book after a recap of two multifamily assets.',
    products: ['Cash management', 'Personal SMA'],
    tone: 'Crisp, Bay Area understated',
    notes: 'Referred by Marcus Chen. Just closed a recap. Cash sitting at a regional bank.',
    priorNotes: 'Marcus texted an intro on 8/10.',
    lastTouch: '2026-08-10',
    nextTouch: '2026-08-16',
    owner: 'James',
    source: 'Chen referral',
  },
  {
    id: 'p-adler',
    name: 'George Adler',
    company: 'Adler Medical Devices',
    title: 'Executive Chairman',
    website: 'https://adlermed.example',
    linkedin: 'https://linkedin.com/in/georgeadler',
    industry: 'Medtech',
    email: 'george@adlermed.example',
    phone: '(858) 555-0119',
    city: 'San Diego, CA',
    stage: 'commit',
    relationshipStatus: 'active-dialogue',
    objective: 'Close a $2.4M personal book and a small Fund IV ticket from the family LLC.',
    products: ['Personal SMA', 'Fund IV'],
    tone: 'Formal, measured',
    notes: 'Sold 60% to a strategics last year. Wife is the economic decision maker on the family LLC.',
    priorNotes: 'Term sheet verbally accepted 8/4. Waiting on LLC operating-agreement addendum.',
    lastTouch: '2026-08-04',
    nextTouch: '2026-08-15',
    owner: 'James',
    source: 'Conference',
  },
  {
    id: 'p-qureshi',
    name: 'Yasmin Qureshi',
    company: 'Qureshi Holdings',
    title: 'Principal',
    website: 'https://qureshihold.example',
    linkedin: 'https://linkedin.com/in/yasminq',
    industry: 'Family holding company',
    email: 'yasmin@qureshihold.example',
    phone: '(713) 555-0166',
    city: 'Houston, TX',
    stage: 'discovery',
    relationshipStatus: 'warm',
    objective: 'Map the holding company vs. personal balance sheet and find the first Solyco entry point.',
    products: ['OCIO satellite', 'PE allocation'],
    tone: 'Curious, precise',
    notes: 'Second generation. Energy + logistics. Wants ESG language that is not decorative.',
    priorNotes: 'Zoom on 7/28. She asked for a one-page on how we underwrite industrial decarbonization.',
    lastTouch: '2026-07-28',
    nextTouch: '2026-08-20',
    owner: 'James',
    source: 'Inbound',
  },
  {
    id: 'p-holm',
    name: 'Peter Holm',
    company: 'Holm Beverage Co',
    title: 'Owner',
    website: 'https://holmbev.example',
    linkedin: 'https://linkedin.com/in/peterholm',
    industry: 'Cpg / beverage',
    email: 'peter@holmbev.example',
    phone: '(612) 555-0139',
    city: 'Minneapolis, MN',
    stage: 'nurture',
    relationshipStatus: 'cold',
    objective: 'Stay on the radar until the brand’s regional expansion settles.',
    products: ['Growth equity'],
    tone: 'Casual, founder-friendly',
    notes: 'Went quiet after a distributor shakeup. Do not chase.',
    priorNotes: 'Last reply 5/3: “circle back in the fall.”',
    lastTouch: '2026-05-03',
    nextTouch: '2026-09-08',
    owner: 'James',
    source: 'Cold outreach',
  },
  {
    id: 'p-brooks',
    name: 'Natalie Brooks',
    company: 'Brooks Family Office',
    title: 'Director of Investments',
    website: 'https://brooksfo.example',
    linkedin: 'https://linkedin.com/in/nataliebrooks',
    industry: 'Single-family office',
    email: 'natalie@brooksfo.example',
    phone: '(704) 555-0127',
    city: 'Charlotte, NC',
    stage: 'proposal',
    relationshipStatus: 'active-dialogue',
    objective: 'Win a $5M Fund IV ticket and a co-invest right on the next services deal.',
    products: ['Fund IV', 'Co-invest'],
    tone: 'Institutional, concise',
    notes: 'Office is professionalizing. She used to be at a fund-of-funds. Will grill on attribution.',
    priorNotes: 'Data room opened 8/1. She flagged our 2023 DPI.',
    lastTouch: '2026-08-11',
    nextTouch: '2026-08-19',
    owner: 'James',
    source: 'Park introduction',
  },
]

const touchpoints: Touchpoint[] = [
  { id: 't1', subjectId: 'm-voss', subjectType: 'member', kind: 'meeting', title: 'Liquidity + Fund IV', date: '2026-08-15', status: 'due', notes: 'Bring Park Ave close timeline.' },
  { id: 't2', subjectId: 'm-shah', subjectType: 'member', kind: 'meeting', title: 'Quarterly + IPS', date: '2026-08-15', status: 'due', notes: 'Print packet for Ravi.' },
  { id: 't3', subjectId: 'p-smith', subjectType: 'prospect', kind: 'meeting', title: 'Intro: liquidity & succession', date: '2026-08-15', status: 'due', notes: 'Whitaker warm intro. Brother is the landmine.' },
  { id: 't4', subjectId: 'm-alvarez', subjectType: 'member', kind: 'call', title: 'Consolidation check-in', date: '2026-08-16', status: 'planned', notes: 'Do not rush custodians.' },
  { id: 't5', subjectId: 'p-lin', subjectType: 'prospect', kind: 'call', title: 'Chen intro follow-up', date: '2026-08-16', status: 'planned', notes: 'Cash sitting idle at a regional.' },
  { id: 't6', subjectId: 'p-nguyen', subjectType: 'prospect', kind: 'email', title: 'Ask for 2025 audit', date: '2026-08-16', status: 'planned', notes: '' },
  { id: 't7', subjectId: 'm-whitaker', subjectType: 'member', kind: 'personal', title: 'Anniversary note for Ruth & James', date: '2026-08-18', status: 'planned', notes: 'Cleveland maker, not catalog.' },
  { id: 't8', subjectId: 'm-okonkwo', subjectType: 'member', kind: 'call', title: 'Morehouse / education funding', date: '2026-08-19', status: 'planned', notes: 'Son committed.' },
  { id: 't9', subjectId: 'p-brooks', subjectType: 'prospect', kind: 'meeting', title: 'DPI deep-dive', date: '2026-08-19', status: 'planned', notes: 'She will come with a model.' },
  { id: 't10', subjectId: 'm-chen', subjectType: 'member', kind: 'market-update', title: 'Lockup / 10b5-1 reminder', date: '2026-08-20', status: 'planned', notes: 'November lockup.' },
  { id: 't11', subjectId: 'p-ortiz', subjectType: 'prospect', kind: 'call', title: 'DSO recap pulse', date: '2026-08-17', status: 'planned', notes: '' },
  { id: 't12', subjectId: 'p-holm', subjectType: 'prospect', kind: 'email', title: 'Fall circle-back', date: '2026-09-08', status: 'planned', notes: 'Do not chase before this.' },
  { id: 't13', subjectId: 'm-hale', subjectType: 'member', kind: 'referral', title: 'Feeder term sheet', date: '2026-08-22', status: 'planned', notes: 'His two partners.' },
  { id: 't14', subjectId: 'm-voss', subjectType: 'member', kind: 'personal', title: 'Peonies after Park Ave close', date: '2026-10-20', status: 'planned', notes: 'Never lilies.' },
  { id: 't15', subjectId: 'p-adler', subjectType: 'prospect', kind: 'email', title: 'LLC addendum nudge', date: '2026-08-15', status: 'due', notes: 'Wife is the economic buyer.' },
]

const meetings: Meeting[] = [
  {
    id: 'mt-shah',
    title: 'Priya Shah — quarterly review',
    when: '2026-08-15T09:30:00',
    durationMin: 45,
    location: 'Zoom',
    kind: 'external',
    objective: 'Walk Q2 performance, refresh the IPS, and test a $3M Fund IV add.',
    attendeeIds: [{ type: 'member', id: 'm-shah' }],
    agenda: [
      'Q2 performance vs. IPS',
      'Muni book duration after the July rally',
      'Fund IV add — $3M',
      'Successor-trustee contact',
      'Same-day written recap',
    ],
    status: 'upcoming',
    revealed: 0,
    script: [
      { id: 'ts1', atSec: 0, speaker: 'James', text: 'Priya — thanks for making the morning. I sent the packet last night so Ravi has the printed set.' },
      { id: 'ts2', atSec: 4, speaker: 'Priya Shah', text: 'He already marked it up. He wants to know why munis lagged the July rally and whether we should extend duration.' },
      { id: 'ts3', atSec: 8, speaker: 'James', text: 'Fair. We stayed short on purpose into the cut. If we extend, I would do it inside the existing SMA, not by adding a fund.' },
      { id: 'ts4', atSec: 12, speaker: 'Priya Shah', text: 'That is fine. The other thing — Anika called from London. She is asking questions about the trust again. I do not want her on it, but I also do not want a fight.' },
      { id: 'ts5', atSec: 16, speaker: 'James', text: 'We can keep the economic terms exactly as they are and still give her an information right. No control. I will draft language, not send anything.' },
      { id: 'ts6', atSec: 20, speaker: 'Priya Shah', text: 'Good. And Fund IV — three million is the number if the muni income stays intact. I will not starve the income book for a PE ticket.' },
      { id: 'ts7', atSec: 24, speaker: 'James', text: 'Understood. We can fund calls from the taxable joint account and leave the trust munis alone. I will show you the path in the recap.' },
    ],
    internalNotes: '',
    externalNotes: '',
  },
  {
    id: 'mt-smith',
    title: 'John Smith — intro (liquidity & succession)',
    when: '2026-08-15T11:00:00',
    durationMin: 60,
    location: 'Solyco — conference room',
    kind: 'external',
    objective: 'Discuss business liquidity, cash management, succession planning, and personal wealth planning.',
    attendeeIds: [{ type: 'prospect', id: 'p-smith' }],
    agenda: [
      'How Smith Manufacturing actually makes money',
      'Working-capital pressure',
      'Brother as COO — succession landmines',
      'Personal vs. corporate liquidity',
      'Whether a minority recap is even the right tool',
      'Next step if there is a pulse',
    ],
    status: 'upcoming',
    revealed: 0,
    script: [
      { id: 'sm1', atSec: 0, speaker: 'James', text: 'John — James Whitaker said I should not waste your time, so I will not. You mentioned working capital and a key-person gap. Which one is keeping you up?' },
      { id: 'sm2', atSec: 4, speaker: 'John Smith', text: 'Working capital, this year. We took two big OEM contracts and the receivables are slower than I priced. The bank line is at 70 percent. I do not want to tap it further.' },
      { id: 'sm3', atSec: 8, speaker: 'James', text: 'So this is a cash-conversion problem, not a “I want to sell the company” problem. That changes the first move.' },
      { id: 'sm4', atSec: 12, speaker: 'John Smith', text: 'Right. The sale conversation is my brother’s nightmare. He runs the floor. If I even say “recap” he hears “outsiders in the building.”' },
      { id: 'sm5', atSec: 16, speaker: 'James', text: 'Then we do not start there. We start with a corporate cash-management sleeve and a personal plan that does not require a transaction. Recap stays in the drawer.' },
      { id: 'sm6', atSec: 20, speaker: 'John Smith', text: 'I also have no one who can sign checks if I am on a table. My wife is on the account but she has never been in the building. That scares me more than the bank line.' },
      { id: 'sm7', atSec: 24, speaker: 'James', text: 'That is a same-week fix — authorized signer, a simple continuity memo, and a personal disability gap check. We can do that without a banker in the room.' },
      { id: 'sm8', atSec: 28, speaker: 'John Smith', text: 'Whitaker said you would not pitch me a fund on the first meeting. Do not prove him wrong.' },
      { id: 'sm9', atSec: 32, speaker: 'James', text: 'I will not. If we do anything next it is a cash map and a succession one-pager for you and your brother. No term sheet.' },
    ],
    internalNotes: '',
    externalNotes: '',
  },
  {
    id: 'mt-internal',
    title: 'Internal — Monday pipeline',
    when: '2026-08-15T14:00:00',
    durationMin: 30,
    location: 'War room',
    kind: 'internal',
    objective: 'Rank live deals, assign the Adler close, and decide whether Holm stays on the board.',
    attendeeIds: [],
    agenda: ['Adler close path', 'Nguyen valuation gap', 'Brooks DPI answers', 'Holm: nurture or drop', 'Trades CSV from this morning'],
    status: 'upcoming',
    revealed: 0,
    script: [
      { id: 'in1', atSec: 0, speaker: 'James', text: 'Adler first. Verbal yes on 8/4. Blocker is the family LLC addendum — his wife is the economic buyer. Who is calling her?' },
      { id: 'in2', atSec: 4, speaker: 'Associate', text: 'I can send the redline today. I would not cold-call her. George should walk it in.' },
      { id: 'in3', atSec: 8, speaker: 'James', text: 'Agreed. Holm we leave until September. Do not manufacture a reason to email him.' },
    ],
    internalNotes: '',
    externalNotes: '',
  },
  {
    id: 'mt-voss',
    title: 'Eleanor Voss — liquidity & Fund IV',
    when: '2026-08-15T16:00:00',
    durationMin: 45,
    location: 'Her office, 641 Park',
    kind: 'external',
    objective: 'Confirm Park Ave close timing and shape a $4–6M Fund IV path that does not disturb the muni sleeve.',
    attendeeIds: [{ type: 'member', id: 'm-voss' }],
    agenda: [
      'Park Ave close — mid-October still?',
      'Where the proceeds sit for 90 days',
      'Fund IV commitment vs. SMA',
      'Clara / art-backed lending curiosity',
      'Henry’s DAF',
    ],
    status: 'upcoming',
    revealed: 0,
    script: [
      { id: 'vo1', atSec: 0, speaker: 'James', text: 'Eleanor. I will not stay long — you have Claremont in the morning. Is October 14th still the close?' },
      { id: 'vo2', atSec: 4, speaker: 'Eleanor Voss', text: 'The lawyers say the 16th. Same week. I do not want that cash sitting in the checking account the bank already tried to “optimize” for me.' },
      { id: 'vo3', atSec: 8, speaker: 'James', text: 'We park it in the taxable SMA, T-bills, and decide on Fund IV after you have lived with the number for two weeks. No commitment from a closing table.' },
      { id: 'vo4', atSec: 12, speaker: 'Eleanor Voss', text: 'Clara asked again about using a painting as collateral. I told her I would mention it. I am not interested in turning the apartment into a balance sheet.' },
      { id: 'vo5', atSec: 16, speaker: 'James', text: 'Then we give Clara a clean no, and a yes on something else — a small advisory seat on the art-world names we already cover. Keeps her close without a loan against the wall.' },
      { id: 'vo6', atSec: 20, speaker: 'Eleanor Voss', text: 'Henry wants a donor-advised fund so he can look serious at Stern. Fine. Small. His name, my money, my veto.' },
    ],
    internalNotes: '',
    externalNotes: '',
  },
  {
    id: 'mt-brooks',
    title: 'Natalie Brooks — DPI follow-up',
    when: '2026-08-19T10:00:00',
    durationMin: 40,
    location: 'Teams',
    kind: 'external',
    objective: 'Defend 2023 DPI with a clean bridge and ask for the $5M Fund IV ticket.',
    attendeeIds: [{ type: 'prospect', id: 'p-brooks' }],
    agenda: ['DPI bridge', 'Whitaker realization path', 'Co-invest rights', 'Next IC date'],
    status: 'upcoming',
    revealed: 0,
    script: [],
    internalNotes: '',
    externalNotes: '',
  },
]

const comms: CommsEvent[] = [
  { id: 'c1', channel: 'email', direction: 'in', subjectId: 'm-voss', subjectType: 'member', occurredAt: '2026-08-15T07:12:00', summary: 'New email from Eleanor Voss', seen: false },
  { id: 'c2', channel: 'phone', direction: 'in', subjectId: 'p-adler', subjectType: 'prospect', occurredAt: '2026-08-15T08:04:00', summary: 'Missed call — George Adler', seen: false },
  { id: 'c3', channel: 'email', direction: 'in', subjectId: 'm-shah', subjectType: 'member', occurredAt: '2026-08-15T08:41:00', summary: 'New email from Priya Shah', seen: false },
  { id: 'c4', channel: 'text', direction: 'in', subjectId: 'm-chen', subjectType: 'member', occurredAt: '2026-08-14T21:18:00', summary: 'New text from Marcus Chen', seen: true },
  { id: 'c5', channel: 'email', direction: 'out', subjectId: 'p-brooks', subjectType: 'prospect', occurredAt: '2026-08-14T16:02:00', summary: 'You emailed Natalie Brooks', seen: true },
  { id: 'c6', channel: 'email', direction: 'in', subjectId: 'm-alvarez', subjectType: 'member', occurredAt: '2026-08-14T11:33:00', summary: 'New email from Sofia Alvarez', seen: true },
  { id: 'c7', channel: 'phone', direction: 'out', subjectId: 'm-whitaker', subjectType: 'member', occurredAt: '2026-08-13T09:05:00', summary: 'You called James Whitaker', seen: true },
  { id: 'c8', channel: 'email', direction: 'in', subjectId: 'p-nguyen', subjectType: 'prospect', occurredAt: '2026-08-13T15:44:00', summary: 'New email from Thomas Nguyen', seen: true },
  { id: 'c9', channel: 'text', direction: 'in', subjectId: 'm-hale', subjectType: 'member', occurredAt: '2026-08-12T06:51:00', summary: 'New text from Robert Hale', seen: true },
  { id: 'c10', channel: 'email', direction: 'in', subjectId: 'p-lin', subjectType: 'prospect', occurredAt: '2026-08-10T18:20:00', summary: 'New email from Margaret Lin', seen: true },
]

const trades: Trade[] = [
  {
    id: 'tr1',
    date: '2026-08-15',
    symbol: 'BIL',
    side: 'buy',
    quantity: 12000,
    price: 91.62,
    accountCode: 'VOSS-TX-110',
    clientHint: 'Voss',
    status: 'pending',
    fanout: [{ memberId: 'm-voss', accountId: 'a-v1', accountCode: 'VOSS-TX-110' }],
  },
  {
    id: 'tr2',
    date: '2026-08-15',
    symbol: 'MUB',
    side: 'buy',
    quantity: 4000,
    price: 106.18,
    accountCode: 'SHAH-TR-091',
    clientHint: 'Shah Trust',
    status: 'pending',
    fanout: [{ memberId: 'm-shah', accountId: 'a-s1', accountCode: 'SHAH-TR-091' }],
  },
  {
    id: 'tr3',
    date: '2026-08-15',
    symbol: 'NVDA',
    side: 'sell',
    quantity: 350,
    price: 178.4,
    accountCode: 'CHEN-TX-330',
    clientHint: 'Chen',
    status: 'pending',
    fanout: [{ memberId: 'm-chen', accountId: 'a-c1', accountCode: 'CHEN-TX-330' }],
  },
  {
    id: 'tr4',
    date: '2026-08-15',
    symbol: 'VCSH',
    side: 'buy',
    quantity: 6200,
    price: 78.91,
    accountCode: 'OKON-TX-441',
    clientHint: 'Okonkwo',
    status: 'pending',
    fanout: [{ memberId: 'm-okonkwo', accountId: 'a-o1', accountCode: 'OKON-TX-441' }],
  },
  {
    id: 'tr5',
    date: '2026-08-15',
    symbol: 'VTI',
    side: 'buy',
    quantity: 800,
    price: 328.55,
    accountCode: 'WHIT-TX-208',
    clientHint: 'Whitaker',
    status: 'pending',
    fanout: [{ memberId: 'm-whitaker', accountId: 'a-w1', accountCode: 'WHIT-TX-208' }],
  },
  {
    id: 'tr6',
    date: '2026-08-15',
    symbol: 'SGOV',
    side: 'buy',
    quantity: 9000,
    price: 100.42,
    accountCode: 'ALVA-TR-55',
    clientHint: 'Alvarez',
    status: 'pending',
    fanout: [{ memberId: 'm-alvarez', accountId: 'a-al1', accountCode: 'ALVA-TR-55' }],
  },
  {
    id: 'tr7',
    date: '2026-08-15',
    symbol: 'AAPL',
    side: 'sell',
    quantity: 200,
    price: 226.1,
    accountCode: 'HALE-TX-04',
    clientHint: 'Hale personal',
    status: 'pending',
    fanout: [{ memberId: 'm-hale', accountId: 'a-h2', accountCode: 'HALE-TX-04' }],
  },
  {
    id: 'tr8',
    date: '2026-08-15',
    symbol: 'IEFA',
    side: 'buy',
    quantity: 1500,
    price: 84.22,
    accountCode: 'PARK-TR-77',
    clientHint: 'Park Trust',
    status: 'pending',
    fanout: [{ memberId: 'm-park', accountId: 'a-p2', accountCode: 'PARK-TR-77' }],
  },
]

const integrations: Integration[] = [
  { id: 'i-outlook', name: 'Email', vendor: 'Outlook', category: 'comms', status: 'simulated', lastSync: '2026-08-15T08:55:00', detail: 'Presence only — no message bodies. New inbound flags land in Comms.' },
  { id: 'i-phone', name: 'Phone & SMS', vendor: 'Carrier / desk', category: 'comms', status: 'simulated', lastSync: '2026-08-15T08:55:00', detail: 'Missed-call and text presence. Content is never pulled in.' },
  { id: 'i-cal', name: 'Calendar', vendor: 'Microsoft 365', category: 'calendar', status: 'simulated', lastSync: '2026-08-15T07:00:00', detail: 'Today’s meetings are mirrored into Daily Prep. No live calendar write-back.' },
  { id: 'i-news', name: 'Financial news', vendor: 'Desk feed', category: 'market', status: 'simulated', lastSync: '2026-08-15T06:30:00', detail: 'Morning tape used to compose the Daily Market Brief.' },
  { id: 'i-orion', name: 'Account list', vendor: 'Orion', category: 'custodian', status: 'simulated', lastSync: '2026-08-15T06:10:00', detail: 'Member accounts and AUM. Demo snapshot — not a live NAV.' },
  { id: 'i-nitro', name: 'Risk profile', vendor: 'Nitrogen', category: 'risk', status: 'idle', lastSync: '2026-08-12T09:00:00', detail: 'Questionnaire scores stored on each member. No live scoring.' },
  { id: 'i-edge', name: 'Edge Tech approvals', vendor: 'Edge Tech', category: 'approvals', status: 'attention', lastSync: '2026-08-15T08:20:00', detail: 'Two items waiting in the Launch Pad approvals queue.' },
  { id: 'i-csv', name: 'Daily trades CSV', vendor: 'Email attachment', category: 'file', status: 'attention', lastSync: '2026-08-15T06:02:00', detail: 'Morning positions/trades file. Ingest is simulated; approval is human.' },
  { id: 'i-li', name: 'LinkedIn', vendor: 'LinkedIn', category: 'social', status: 'idle', lastSync: '2026-08-01T12:00:00', detail: 'Not wired. Profile URLs are stored on prospects only.' },
]

const approvals: EdgeApproval[] = [
  {
    id: 'e1',
    title: 'Capital-call notice — Solyco Fund III',
    source: 'Edge Tech',
    detail: 'Priya Shah · $180,000 · due 2026-08-28. Confirm wiring instructions on SHAH-TR-091 before release.',
    status: 'pending',
    createdAt: '2026-08-15T08:20:00',
  },
  {
    id: 'e2',
    title: 'K-1 delivery method change',
    source: 'Edge Tech',
    detail: 'Eleanor Voss requested electronic K-1s for VOSS-TR-204. Needs a wet-ink authorization on file — none on record.',
    status: 'pending',
    createdAt: '2026-08-14T16:40:00',
  },
  {
    id: 'e3',
    title: 'Address change — Harbor Ridge',
    source: 'Edge Tech',
    detail: 'David Okonkwo · new registered agent address. Low risk; still requires a second set of eyes.',
    status: 'pending',
    createdAt: '2026-08-13T11:15:00',
  },
]

export const SEED_VERSION = 1

export function buildSeed(): AppState {
  return {
    members,
    prospects,
    touchpoints,
    meetings,
    comms,
    trades,
    integrations,
    drafts: [],
    artifacts: [],
    approvals,
    posted: [],
    liveMeetingId: null,
  }
}
